; Fast test profile for OSM land polygons

[dataset]
land_geojson = dataset/osm_land_istanbul_genoa.geojson

[tss]
geojson = dataset/osm_tss_istanbul_genoa.geojson

[mesh]
grid_step_deg = 0.02
narrow_refine_step_deg = 0.01
min_lat = 35
max_lat = 46
min_lon = 3
max_lon = 42
corridor_lat_pad_deg = 3.0
corridor_lon_pad_deg = 3.0

[safety]
coastline_clearance_m = 100

[route]
start_name = Izmir
start_lat = 40.8974
start_lon = 28.9517
goal_name = Venedik
goal_lat = 37.95
goal_lon = 20.44

[cache]
use_cache = false
build_cache_file = cache/triangulationdataset_marmara_straits_g01_c100.bin

[output]
svg_file = output/PlannedRouteMarmara.svg
