# RotaOptimaldsCpp scenario file
# waypoint format:
# waypoint = X,Y,psig,Kf,tol,use_Kf,w_wp,hit_scale
# optional alanlar icin bos/none kullanabilirsin.

N_MPC = 20

ds_min = 0.01
ds_max = 5.0
K_max = 0.1
S_max = 14
nseg = 2

w_pos = 50.0
w_psi = 50.0
w_K = 1.0
w_Kcmd = 0.25
w_dKcmd = 15.0
w_ds_smooth = 0.001
ds_jump_max = 0.0
w_Kf = 15.0

w_prog = 0.0
alpha_prog = 0.0
hit_ratio = 0.7

block_lengths_Kcmd = 1,1,2,2,2,2,2,2,2,2,2
block_lengths_ds   = 1,1,2,2,2,2,2,2,2,2,2

x0 = 0.0
y0 = 0.0
psi0 = 0.0
K0 = 0.0

tol_default = 2.5
max_iters = 300
use_heading_gate = true
tol_psi_deg = 12.0
w_wp_intermediate = 5.0
term_scale_intermediate = 0.2
term_scale_final = 1.0
hit_scale_intermediate = 0.7
w_wp_final = 1.0
use_wp_kf = true
kf_fallback = 0.0

waypoint = 40.0,  40.0,  1.57,   -0.025, 0.5, true,,
waypoint =  0.0,  80.0,  3.14,   -0.025, 0.5, true,,
waypoint =-40.0,  40.0,  4.71,   -0.025, 0.5, true,,
waypoint =-0.0, 0.0,  0,         -0.025, 0.5, true,,
